from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN
import io


def split_text(text, max_chars):
    """Smart algorithm to split long text into chunks without cutting words in half."""
    words = text.split()
    chunks = []
    current_chunk = ""
    for word in words:
        if len(current_chunk) + len(word) + 1 <= max_chars:
            current_chunk += (word + " ")
        else:
            chunks.append(current_chunk.strip())
            current_chunk = word + " "
    if current_chunk:
        chunks.append(current_chunk.strip())
    return chunks


def create_presentation(agent_data):
    prs = Presentation()

    def add_base_slide(title_text):
        """Helper function to stamp our neon template onto any new slide."""
        slide_layout = prs.slide_layouts[5]  # Blank canvas
        slide = prs.slides.add_slide(slide_layout)

        # --- 1. DEEP VOID BACKGROUND ---
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor(10, 15, 25)

        # --- 2. NEON CYAN ACCENT BAR ---
        left_bar = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0), Inches(0), Inches(0.15), Inches(7.5))
        left_bar.fill.solid()
        left_bar.fill.fore_color.rgb = RGBColor(0, 229, 255)
        left_bar.line.fill.background()

        # --- 3. BRANDING FOOTER ---
        footer = slide.shapes.add_textbox(Inches(7.5), Inches(7.1), Inches(2), Inches(0.4))
        tf_footer = footer.text_frame
        run = tf_footer.paragraphs[0].add_run()
        run.text = "⚡ Generated by Nexus AI"
        run.font.color.rgb = RGBColor(100, 116, 139)
        run.font.size = Pt(10)

        # --- 4. TITLE FORMATTING ---
        title_shape = slide.shapes.title
        if title_shape:
            title_shape.text = title_text
            title_shape.left = Inches(0.5)
            title_shape.top = Inches(0.3)
            title_shape.width = Inches(8.5)
            title_shape.height = Inches(1.2)

            tf = title_shape.text_frame
            tf.word_wrap = True

            for paragraph in tf.paragraphs:
                paragraph.alignment = PP_ALIGN.LEFT
                for run in paragraph.runs:
                    run.font.name = 'Arial'
                    run.font.size = Pt(36)
                    run.font.color.rgb = RGBColor(0, 229, 255)
                    run.font.bold = True
        return slide

    for slide_info in agent_data:
        layout_type = slide_info.get('layout', 'bullets')
        base_title = slide_info.get('title', 'Untitled Slide')
        content = slide_info.get('content', '')

        if layout_type == 'table':
            slide = add_base_slide(base_title)
            rows_data = content.split('|')
            num_rows = len(rows_data)
            num_cols = len(rows_data[0].split(',')) if num_rows > 0 else 2

            x, y, cx, cy = Inches(0.5), Inches(1.8), Inches(9), Inches(3)
            table_shape = slide.shapes.add_table(num_rows, num_cols, x, y, cx, cy).table

            for r_idx, row_text in enumerate(rows_data):
                cols = row_text.split(',')
                for c_idx, cell_text in enumerate(cols):
                    if c_idx < num_cols:
                        cell = table_shape.cell(r_idx, c_idx)
                        cell.text = cell_text.strip()
                        cell.fill.solid()
                        if r_idx == 0:
                            cell.fill.fore_color.rgb = RGBColor(0, 229, 255)
                        else:
                            cell.fill.fore_color.rgb = RGBColor(30, 41, 59)

                        for paragraph in cell.text_frame.paragraphs:
                            for run in paragraph.runs:
                                run.font.color.rgb = RGBColor(10, 15, 25) if r_idx == 0 else RGBColor(255, 255, 255)
                                run.font.name = 'Arial'

        else:
            # --- THE MAGIC: AUTO-PAGINATION ---
            MAX_CHARS = 650  # The safe character limit for our neon text boxes
            chunks = split_text(content, MAX_CHARS)

            # Fallback if the AI returns empty content
            if not chunks:
                chunks = [""]

            for i, chunk in enumerate(chunks):
                # Append (Cont.) to the title if it spilled over!
                title = base_title if i == 0 else f"{base_title} (Cont.)"
                slide = add_base_slide(title)

                # --- VIBRANT CONTENT BOXES ---
                x, y, cx, cy = Inches(0.5), Inches(1.8), Inches(9), Inches(4.5)
                shape = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, x, y, cx, cy)

                shape.fill.solid()
                shape.fill.fore_color.rgb = RGBColor(15, 23, 42)
                shape.line.color.rgb = RGBColor(236, 72, 153)
                shape.line.width = Pt(2.5)

                tf = shape.text_frame
                tf.word_wrap = True
                tf.text = chunk

                for paragraph in tf.paragraphs:
                    for run in paragraph.runs:
                        run.font.color.rgb = RGBColor(248, 250, 252)
                        run.font.size = Pt(22)
                        run.font.name = 'Arial'

    ppt_stream = io.BytesIO()
    prs.save(ppt_stream)
    ppt_stream.seek(0)
    return ppt_stream